### ISSUE TITLE
Targeted Units Dropout - Why dropout also on test?

### ISSUE THREAD

**Issue by guglielmocamporese** [for-ai/TD#13]
I saw that the targeted dropout on the weights can either select `train` or `test` mode,  instead the targeted dropout on the units is always on `train` mode even when the model does the inference. Is there any reason for that?

- **Targeted Weight Dropout Function:**

`def targeted_weight_dropout(w, params, is_training):`
&nbsp;&nbsp;&nbsp;&nbsp;`drop_rate = params.drop_rate`
&nbsp;&nbsp;&nbsp;&nbsp;`targ_perc = params.targ_rate`
&nbsp;&nbsp;&nbsp;&nbsp;`w_shape = w.shape`
&nbsp;&nbsp;&nbsp;&nbsp;`w = tf.reshape(w, [-1, w_shape[-1]])`
&nbsp;&nbsp;&nbsp;&nbsp;`norm = tf.abs(w)`
&nbsp;&nbsp;&nbsp;&nbsp;`idx = tf.to_int32(targ_perc * tf.to_float(tf.shape(w)[0]))`
&nbsp;&nbsp;&nbsp;&nbsp;`threshold = tf.contrib.framework.sort(norm, axis=0)[idx]`
&nbsp;&nbsp;&nbsp;&nbsp;`mask = norm < threshold[None, :]`
&nbsp;&nbsp;&nbsp;&nbsp;`if not is_training:`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`w = (1. - tf.to_float(mask)) * w`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`w = tf.reshape(w, w_shape)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return w`
&nbsp;&nbsp;&nbsp;&nbsp;`mask = tf.to_float(`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`tf.logical_and(tf.random_uniform(tf.shape(w)) < drop_rate, mask))`
&nbsp;&nbsp;&nbsp;&nbsp;`w = (1. - mask) * w`
&nbsp;&nbsp;&nbsp;&nbsp;`w = tf.reshape(w, w_shape)`
&nbsp;&nbsp;&nbsp;&nbsp;`return w`

https://github.com/for-ai/TD/blob/87cf2a0682274badbfde962023c657779aa79975/models/utils/dropouts.py#L23

- **Targeted Unit Dropout Function:**

`def targeted_unit_dropout(x, params, is_training):`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`w = tf.reshape(x, [-1, x.shape[-1]])`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`norm = tf.norm(w, axis=0)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`idx = int(params.targ_rate * int(w.shape[1]))`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`sorted_norms = tf.contrib.framework.sort(norm)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`threshold = sorted_norms[idx]`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`mask = (norm < threshold)[None, :]`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`mask = tf.tile(mask, [w.shape[0], 1])`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`mask = tf.where(`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`tf.logical_and((1. - params.drop_rate) < tf.random_uniform(tf.shape(w)),`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`mask), tf.ones_like(w, dtype=tf.float32),`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`tf.zeros_like(w, dtype=tf.float32))`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`x = tf.reshape((1 - mask) * w, x.shape)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return x`

https://github.com/for-ai/TD/blob/87cf2a0682274badbfde962023c657779aa79975/models/utils/dropouts.py#L217

**Comment by aidangomez** [comment]
Thanks for pointing this out; targeted unit should also have an in statement similar to targeted weight. We'll update the code.
