### ISSUE TITLE
Variational_dropout and variational_unit_dropout

### ISSUE THREAD

**Issue by lijianyi1997** [for-ai/TD#2]
Hello, I' m confused by the difference between variational_dropout and variational_unit_dropout because I think they are the same through the program. I will be very grateful if you can explain it for me.

**Comment by 1vn** [comment]
Hi @lijianyi1997, thanks for taking the time to look at our code. The difference in the unit implementation is in that we only compute the gates across the last dimension and copy it to every weight in the unit using `tf.tile`.

variational_dropout weight level implementation: https://github.com/for-ai/TD/blob/master/models/utils/dropouts.py#L377

variational_dropout unit level  implementation: https://github.com/for-ai/TD/blob/master/models/utils/dropouts.py#L390
