### ISSUE TITLE
How embed your targeted dropout in other model？

### ISSUE THREAD

**Issue by longmalongma** [for-ai/TD#5]
Hello，think you for your code about the parper of targeted dropout，I see you said It is simultaneously easy to implement, consisting of a two-line change using neural network frameworks such as Tensorflow，I want to which line need to change？How embed your targeted dropout in other model？Expect for your reply。

**Comment by aidangomez** [comment]
Sure here is an example, wherever you are presently using `tf.nn.dropout` in you code right now, use this method instead:

```python3
def targeted_dropout(x, drop_rate, targ_rate, is_training):
  # x is a weight with shape: [in, out]
  # drop_rate is the dropout rate
  # targ_rate is the percentage of elements you intend to prune
  norms = tf.abs(x)
  k = tf.to_int32(tf.to_float(tf.shape(x)[0]) * targ_rate)
  transpose_norms = tf.transpose(norms) # unfortunately this transpose is necessary since top_k only acts on the last dimension
  vals, _ = -tf.nn.top_k(-transpose_norms, k=k)
  threshold = val[-1]
  targ_mask = tf.to_float(norms >= threshold)
  drop_mask = tf.to_float(tf.random.uniform(targ_mask.shape) < drop_rate)
  
  if not is_training:
    return targ_mask * x

  return targ_mask * drop_mask * x
```

**Comment by aidangomez** [comment]
Hopefully this helps!

**Comment by longmalongma** [comment]
Thank you for your reply.I successfully put your code in my model,but when I call the function of targeted dropout,I meet a problem, the problem is:

TypeError: bad operand type for unary -: 'TopKV2'     ,can you help me solve this problem?my these code is that:










------------------ 原始邮件 ------------------
发件人: "Aidan Gomez"<notifications@github.com>;
发送时间: 2019年5月29日(星期三) 下午5:08
收件人: "for-ai/TD"<TD@noreply.github.com>;
抄送: "雄途～～～"<1442342449@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [for-ai/TD] How embed your targeted dropout in other model？ (#5)




Sure here is an example, where ever you are presently using tf.nn.dropout in you code right now, use this method instead:
 def targeted_dropout(x, drop_rate, targ_rate, is_training):   # x is a weight with shape: [in, out]   # drop_rate is the dropout rate   # targ_rate is the percentage of elements you intend to prune   norms = tf.abs(x)   k = tf.to_int32(tf.to_float(tf.shape(x)[0]) * targ_rate)   vals, _ = -tf.nn.top_k(-norms, k=k)   threshold = val[-1]   targ_mask = tf.to_float(norms >= threshold)   drop_mask = tf.to_float(tf.random.uniform(targ_mask.shape) < drop_rate)      if not is_training:     return targ_mask * x   return targ_mask * drop_mask * x

**Comment by aidangomez** [comment]
Please read through and understand the code. There is a bug in it; but the solution is very straightforward.

Look at this line:
```python3
  vals, _ = -tf.nn.top_k(-transpose_norms, k=k)
```

And read the Tensorflow documentation for `tf.nn.top_k`. It returns a pair, and I am applying a negative to a pair: `-tf.nn.top_k(...)` which doesn't make sense.

I'm sure you can figure out the solution yourself.

**Comment by longmalongma** [comment]
Think you for your reply，I see it now.Think you again




------------------ Original ------------------

**Comment by aidangomez** [comment]
My pleasure, best of luck!
