### ISSUE TITLE
where can I call the function of targeted dropout?

### ISSUE THREAD

**Issue by longmalongma** [for-ai/TD#7]
Hello,Think you for your work,I successfully define your targeted dropout'function according your help.In order to let this function work,But now I do not know where can I call this function in my model .
Because dropout in fully-connection layer,is targeted dropout only in fully-connection layer?except for you reply

**Comment by aidangomez** [comment]
You apply this function to your weights in each layer.

So if you have a normal dense layer you can do the following:
```python3
def dense(inputs, num_features, activation, name=None):
  with tf.variable_scope(name, default_name="dense"):
    w = tf.get_variable("weight", shape=[inputs.shape[-1].value, num_features])
    td_w = targeted_dropout(w)  # also put the targ and drop rates here
    y = tf.matmul(inputs, td_w)
    return activation(y)
```

**Comment by longmalongma** [comment]
Can I use this function in fully-connection layer to instead dropout'function？I try it，but result is bad.I do not know why.




------------------ Original ------------------

**Comment by aidangomez** [comment]
I can't debug your code for you. Please open a question on StackOverflow or ask a colleague / peer for help with debugging code.
