### ISSUE TITLE
ValueError: Please wrap optimizers with TowerOptimizer in order to use replicate_model_fn with multiple `devices`

### ISSUE THREAD

**Issue by ghost** [for-ai/TD#9]
Hi,
When i executed the command python3.5 -m TD.train --env=local --hparams=resnet_default
Iam using two 2080Ti GPUs. Kindly please help

i got the error below:

raise ValueError('Please wrap optimizers with TowerOptimizer'
ValueError: Please wrap optimizers with TowerOptimizer in order to use replicate_model_fn with multiple `devices`.

**Comment by ghost** [comment]
@aidangomez , kindly please help

**Comment by aidangomez** [comment]
The error tells you what to do.

> wrap optimizers with TowerOptimizer
